-- rocketflarerev
-- kbotrocketflare
-- rocketflarereversed
-- levelerflare
-- rocketflarekbots
-- krogothflare
-- rocketflare

return {
  ["plasmaflarerev"] = {
    usedefaultexplosions = true,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = 33,
        sidetexture        = [[muzzleside]],
        size               = 6,
        sizegrowth         = 0.75,
        ttl                = 15,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 10,
        particlelife       = 60,
        particlelifespread = 5,
        particlesize       = 0.8,
        particlesizespread = 0.2,
        particlespeed      = 2,
        particlespeedspread = 12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 30,
        particlelife       = 50,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = 2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
  },

  ["kbotrocketflare"] = {
    usedefaultexplosions = true,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.5 0.4 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -33,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 15,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.5 0.4 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 10,
        particlelife       = 60,
        particlelifespread = 5,
        particlesize       = 0.8,
        particlesizespread = 0.2,
        particlespeed      = -2,
        particlespeedspread = -12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.3 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 30,
        particlelife       = 50,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.4, 0.2]],
        dir                = [[-45 r90,-45 r90,-45 r90]],
        length             = 1,
        width              = 22,
      },
    },
  },

  ["rocketflarereversed"] = {
    usedefaultexplosions = true,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = 25,
        sidetexture        = [[muzzleside]],
        size               = 4,
        sizegrowth         = 0.75,
        ttl                = 15,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.01 0.1 0.1 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 10,
        particlelife       = 30,
        particlelifespread = 5,
        particlesize       = 0.8,
        particlesizespread = 0.2,
        particlespeed      = 1,
        particlespeedspread = 12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.15,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 30,
        particlelife       = 25,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 0,
        particlespeedspread = 2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-45 r90,-45 r90,-45 r90]],
        length             = 1,
        width              = 22,
      },
    },
  },

  ["levelerflare"] = {
    usedefaultexplosions = true,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -10,
        sidetexture        = [[muzzleside]],
        size               = -15,
        sizegrowth         = 0.75,
        ttl                = 15,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 10,
        particlelife       = 60,
        particlelifespread = 5,
        particlesize       = 1,
        particlesizespread = 0.2,
        particlespeed      = -2,
        particlespeedspread = -20,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 30,
        particlelife       = 50,
        particlelifespread = 0,
        particlesize       = 2,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = -7,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-45 r90,-45 r90,-45 r90]],
        length             = 0.3,
        width              = 44,
      },
    },
  },

  ["rocketflarekbots"] = {
    usedefaultexplosions = true,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -16,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 15,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 5,
        particlelife       = 30,
        particlelifespread = 5,
        particlesize       = 0.8,
        particlesizespread = 0.2,
        particlespeed      = -2,
        particlespeedspread = -12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 15,
        particlelife       = 25,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
  },

  ["krogothflare"] = {
    usedefaultexplosions = true,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -35,
        sidetexture        = [[muzzleside]],
        size               = -35,
        sizegrowth         = 0.75,
        ttl                = 15,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 30,
        particlelife       = 100,
        particlelifespread = 10,
        particlesize       = 8,
        particlesizespread = 2,
        particlespeed      = -2,
        particlespeedspread = -7,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 20,
        particlelife       = 80,
        particlelifespread = 0,
        particlesize       = 6,
        particlesizespread = 0.1,
        particlespeed      = 0,
        particlespeedspread = -7,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-45 r90,-45 r90,-45 r90]],
        length             = 0.3,
        width              = 88,
      },
    },
  },

  ["rocketflare"] = {
    usedefaultexplosions = true,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -33,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 15,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 10,
        particlelife       = 60,
        particlelifespread = 5,
        particlesize       = 0.8,
        particlesizespread = 0.2,
        particlespeed      = -2,
        particlespeedspread = -12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 30,
        particlelife       = 50,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-45 r90,-45 r90,-45 r90]],
        length             = 1,
        width              = 22,
      },
    },
  },

}

