-- sparks
-- reasparks

return {
  ["sparks"] = {
    usedefaultexplosions = true,
    burnstuff = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[1 1 1 0.01   1 0.7 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 28,
        emitrotspread      = 65,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.45, 0]],
        numparticles       = 2,
        particlelife       = 18,
        particlelifespread = 0,
        particlesize       = 0.,
        particlesizespread = 2.4,
        particlespeed      = 2.3,
        particlespeedspread = 1.8,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[flamespark]],
      },
    },
    groundflash = {
      circlealpha        = 0.2,
      circlegrowth       = 0,
      flashalpha         = 0.1,
      flashsize          = 50,
      ttl                = 15,
      color = {
        [1]  = 0.11999999731779,
        [2]  = 0.30000001192093,
        [3]  = 1,
      },
    },
    heatcloud = {
      air                = true,
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 15,
        heatfalloff        = 1.4,
        maxheat            = 15,
        pos                = [[0.2 r-0.4, 0.8 r-0.1, 0.2 r-0.4]],
        size               = 3.3,
        sizegrowth         = 0.0,
        sizemod            = 4,
        sizemodmod         = 0,
        speed              = [[-0.4 r0.8, -0.1 r0.4, -0.4 r0.8]],
        texture            = [[lightweb1]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.35,
        alphadecay         = 0.1,
        color              = [[0.12, 0.3, 1]],
        dir                = [[-180 r360,-180 r360,-180 r360]],
        length             = 1,
        width              = 1,
      },
    },
  },

  ["reasparks"] = {
    usedefaultexplosions = true,
    heatcloud = {
      air                = true,
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 15,
        heatfalloff        = 1.4,
        maxheat            = 15,
        pos                = [[0.8 r-1.6, 3.0 r-0.4, 0.8 r-1.6]],
        size               = 7.67,
        sizegrowth         = 0.0,
        sizemod            = 7.67,
        sizemodmod         = 0,
        speed              = [[-0.4 r0.8, -0.2 r0.4, -0.4 r0.8]],
        texture            = [[lightweb1]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.35,
        alphadecay         = 0.1,
        color              = [[0.12, 0.3, 1]],
        dir                = [[-180 r360,-180 r360,-180 r360]],
        length             = 5,
        width              = 1,
      },
    },
  },

}

