-- nucklearnanoga2
-- nucklearnano
-- nucklearnanolottiny
-- pinkcrap
-- nucklearnanopt
-- peeweeshine
-- popupshine
-- purpleafterglow
-- nucklearmini
-- fireball
-- nucklearnanomt
-- unitfire
-- redcrap
-- vulcanfx
-- nucklearnanobanish
-- nucklearnanolotfast
-- bloodshine
-- kbotmissiletrail
-- advsam
-- kbotrockettrail
-- t2aakbot
-- nucklearnanosmall
-- dguntrail
-- raventrail
-- nucklearnanotiny
-- mavwick
-- greencrap
-- nucklearnanocatapult
-- nucklearnanocir

return {
  ["nucklearnanoga2"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1 0.7 0.15 0.2 0.1 0.05 0.0 0.2 0.1 0.05 0.0 0.3 0.1 0.05 0.0 0.3]],
        directional        = false,
        emitrot            = 3,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 4,
        particlelifespread = 3,
        particlesize       = 1.2,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 9,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[0.85 0.42 0.0 0.4 0.85 0.42 0.0 0.3 0.2 0.1 0.0 0.3 0.2 0.1 0.0 0.2]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 3,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 4,
        particlelifespread = 3,
        particlesize       = 1.5,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 7,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

  ["nucklearnano"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.7 0.5 0.2 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 4,
        particlelife       = 50,
        particlelifespread = 15,
        particlesize       = 6,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.6 0.35 0.2 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 4,
        particlelife       = 50,
        particlelifespread = 15,
        particlesize       = 6,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.15,
        alwaysvisible      = true,
        color              = [[1.0, 0.5, 0.2]],
        dir                = [[-10 r20,-10 r20,-10 r20]],
        length             = 1,
        width              = 22,
      },
    },
  },

  ["nucklearnanolottiny"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 2.5,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 8,
        particlelife       = 10,
        particlelifespread = 3,
        particlesize       = 0.046875,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 7,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.1 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 2.5,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 8,
        particlelife       = 3,
        particlelifespread = 3,
        particlesize       = 0.03125,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 17,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.6,
      flashsize          = 6,
      ground             = true,
      ttl                = 6,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.69999998807907,
        [3]  = 0.20000000298023,
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -1.5,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

  ["pinkcrap"] = {
    usedefaultexplosions = false,
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.3,
      flashsize          = 40,
      ground             = true,
      ttl                = 40,
      water              = true,
      color = {
        [1]  = 0.33000001311302,
        [2]  = 0,
        [3]  = 1,
      },
    },
  },

  ["nucklearnanopt"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[0.01 0.1 0.1 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 12,
        particlelifespread = 3,
        particlesize       = 1.2,
        particlesizespread = 1,
        particlespeed      = 15,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 1.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[0.01 0.1 0.1 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 12,
        particlelifespread = 3,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 3,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.6,
      flashsize          = 3,
      ground             = true,
      ttl                = 6,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.69999998807907,
        [3]  = 0.20000000298023,
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -1,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

  ["peeweeshine"] = {
    usedefaultexplosions = false,
  },

  ["popupshine"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 0.1,
      circlegrowth       = 0,
      flashalpha         = 0.25,
      flashsize          = 20,
      ttl                = 15,
      color = {
        [1]  = 1,
        [2]  = 0.80000001192093,
        [3]  = 0.20000000298023,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.28,
        color              = [[1.0, 0.8, 0.2]],
        dir                = [[-3 r6,-3 r6,-3 r6]],
        length             = 3,
        width              = 6,
      },
    },
  },

  ["purpleafterglow"] = {
    usedefaultexplosions = false,
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.2,
        color              = [[0.22, 0.066, 1]],
        dir                = [[-10 r20,-10 r20,-10 r20]],
        length             = 1,
        width              = 16,
      },
    },
  },

  ["nucklearmini"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.7 0.5 0.2 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 4,
        particlelife       = 70,
        particlelifespread = 15,
        particlesize       = 13,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.6 0.35 0.2 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 4,
        particlelife       = 70,
        particlelifespread = 15,
        particlesize       = 13,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.08,
        alwaysvisible      = true,
        color              = [[1.0, 0.5, 0.2]],
        dir                = [[-10 r20,-10 r20,-10 r20]],
        length             = 1,
        width              = 22,
      },
    },
  },

  ["fireball"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.77,
        colormap           = [[0.7 0.5 0.4 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 30,
        particlelifespread = 3,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = -1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.3,
      flashsize          = 40,
      ground             = true,
      ttl                = 10,
      water              = true,
      color = {
        [1]  = 0.33000001311302,
        [2]  = 0.20000000298023,
        [3]  = 0.20000000298023,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.5, 0.4]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["nucklearnanomt"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[0.01 0.1 0.1 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.1]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 4,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 12,
        particlelifespread = 3,
        particlesize       = 1.2,
        particlesizespread = 1,
        particlespeed      = 15,
        particlespeedspread = 5,
        pos                = [[0, 1, 0]],
        sizegrowth         = 1.0,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[0.01 0.1 0.1 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 4,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 12,
        particlelifespread = 3,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 4,
        particlespeedspread = 3,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.6,
      flashsize          = 3,
      ground             = true,
      ttl                = 6,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.69999998807907,
        [3]  = 0.20000000298023,
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -1,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

  ["unitfire"] = {
    alwaysvisible      = false,
    useairlos          = false,
    usedefaultexplosions = false,
    exhale2 = {
      air                = true,
      alwaysvisible      = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      useairlos          = false,
      water              = true,
      properties = {
        airdrag            = 0.6,
        alwaysvisible      = false,
        colormap           = [[1.0 0.6 0.2 0.01 0.01 0.01 0.01 0.2 0.05 0.05 0.05 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.8, 0]],
        numparticles       = 16,
        particlelife       = 20,
        particlelifespread = 3,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
        useairlos          = false,
      },
    },
    spikes = {
      air                = true,
      alwaysvisible      = false,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      useairlos          = false,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.75,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["redcrap"] = {
    usedefaultexplosions = false,
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.3,
      flashsize          = 30,
      ground             = true,
      ttl                = 10,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.10000000149012,
        [3]  = 0.10000000149012,
      },
    },
  },

  ["vulcanfx"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.5 0.2 0.5 0.15 0.15 0.15 0.6 0.0 0.0 0.0 0.1]],
        directional        = false,
        emitrot            = 40,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 50,
        particlelife       = 7.5,
        particlelifespread = 3,
        particlesize       = 5,
        particlesizespread = 1,
        particlespeed      = 3,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.7 0.4 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 40,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 40,
        particlelife       = 5,
        particlelifespread = 3,
        particlesize       = 5,
        particlesizespread = 1,
        particlespeed      = 6,
        particlespeedspread = 4,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.8, 0.5]],
        dir                = [[-10 r20,-10 r20,-10 r20]],
        length             = 1,
        width              = 22,
      },
    },
  },

  ["nucklearnanobanish"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.1 0.15 0.15 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 10,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 6,
        particlelife       = 40,
        particlelifespread = 5,
        particlesize       = 0.5,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 4,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.06,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.6 0.35 0.2 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 10,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 6,
        particlelife       = 20,
        particlelifespread = 3,
        particlesize       = 2.5,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.06,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 3,
      },
    },
  },

  ["nucklearnanolotfast"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 2,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 11,
        particlelife       = 10,
        particlelifespread = 3,
        particlesize       = 0.046875,
        particlesizespread = 1,
        particlespeed      = 15,
        particlespeedspread = 10,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 2,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 11,
        particlelife       = 3,
        particlelifespread = 3,
        particlesize       = 0.03125,
        particlesizespread = 1,
        particlespeed      = 15,
        particlespeedspread = 10,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.6,
      flashsize          = 6,
      ground             = true,
      ttl                = 6,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.69999998807907,
        [3]  = 0.20000000298023,
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -6,
        sidetexture        = [[muzzleside]],
        size               = -1.5,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

  ["bloodshine"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 0.1,
      circlegrowth       = 0,
      flashalpha         = 0.25,
      flashsize          = 20,
      ttl                = 15,
      color = {
        [1]  = 1,
        [2]  = 0.33000001311302,
        [3]  = 0,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.28,
        color              = [[1, 0.33, 0.0]],
        dir                = [[-4 r6,-4 r8,-4 r8]],
        length             = 4,
        width              = 8,
      },
    },
  },

  ["kbotmissiletrail"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 10,
        particlelifespread = 3,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 1.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 20,
        particlelifespread = 3,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.3,
      flashsize          = 30,
      ground             = true,
      ttl                = 6,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.69999998807907,
        [3]  = 0.20000000298023,
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -12,
        sidetexture        = [[muzzleside]],
        size               = -3,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["advsam"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1 0.88 0.15 0.2 0.7 0.7 0.7 0.2 0.5 0.5 0.5 0.3 0.5 0.5 0.5 0.3]],
        directional        = false,
        emitrot            = 3,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 1,
        particlelifespread = 3,
        particlesize       = 2.5,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 15,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[0.95 0.58 0.0 0.4 0.85 0.42 0.0 0.3 0.0 0.0 0.0 0.3 0.0 0.0 0.0 0.2]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 3,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 2,
        particlelifespread = 3,
        particlesize       = 4,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 14,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

  ["t2aakbot"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1 0.88 0.15 0.2 0.7 0.7 0.7 0.2 0.5 0.5 0.5 0.3 0.5 0.5 0.5 0.3]],
        directional        = false,
        emitrot            = 3,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 7,
        particlelife       = 1,
        particlelifespread = 3,
        particlesize       = 1,
        particlesizespread = 0.5,
        particlespeed      = 10,
        particlespeedspread = 8,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[0.95 0.58 0.0 0.4 0.85 0.42 0.0 0.3 0.0 0.0 0.0 0.3 0.0 0.0 0.0 0.2]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 3,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 7,
        particlelife       = 1.5,
        particlelifespread = 3,
        particlesize       = 2,
        particlesizespread = 0.5,
        particlespeed      = 10,
        particlespeedspread = 7,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

  ["nucklearnanosmall"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.1 0.15 0.15 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 18,
        emitrotspread      = 3,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 6,
        particlelife       = 40,
        particlelifespread = 5,
        particlesize       = 0.5,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.06,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        alwaysvisible      = true,
        colormap           = [[0.6 0.35 0.2 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 18,
        emitrotspread      = 3,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 4,
        particlelife       = 20,
        particlelifespread = 3,
        particlesize       = 2.5,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.06,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 3,
      },
    },
  },

  ["dguntrail"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.67,
        alwaysvisible      = true,
        colormap           = [[0.7 0.5 0.2 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 30,
        particlelifespread = 15,
        particlesize       = 6,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.67,
        alwaysvisible      = true,
        colormap           = [[0.6 0.35 0.2 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 30,
        particlelifespread = 15,
        particlesize       = 6,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.2,
        alwaysvisible      = true,
        color              = [[1.0, 0.5, 0.2]],
        dir                = [[-5 r10,-5 r10,-5 r10]],
        length             = 1,
        width              = 22,
      },
    },
  },

  ["raventrail"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -33,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 10,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 5,
        particlelife       = 60,
        particlelifespread = 5,
        particlesize       = 0.8,
        particlesizespread = 0.2,
        particlespeed      = -2,
        particlespeedspread = -12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 5,
        particlelife       = 50,
        particlelifespread = 0,
        particlesize       = 2,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 1,
        width              = 11,
      },
    },
  },

["catapulttrail"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -33,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 10,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 5,
        particlelife       = 30,
        particlelifespread = 5,
        particlesize       = 0.8,
        particlesizespread = 0.2,
        particlespeed      = -2,
        particlespeedspread = -12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 5,
        particlelife       = 20,
        particlelifespread = 0,
        particlesize       = 2,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.35,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 1,
        width              = 11,
      },
    },
  },


  ["nucklearnanotiny"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 10,
        particlelifespread = 3,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 1.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.6 0.2 0.01 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 20,
        particlelifespread = 3,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.3,
      flashsize          = 15,
      ground             = true,
      ttl                = 6,
      water              = true,
      color = {
        [1]  = 0.89999997615814,
        [2]  = 0.69999998807907,
        [3]  = 0.20000000298023,
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.7 0.2 0.01 0.3 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -12,
        sidetexture        = [[muzzleside]],
        size               = -3,
        sizegrowth         = 0.2,
        ttl                = 2,
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 5,
      },
    },
  },

  ["mavwick"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        colormap           = [[1.0 0.7 0.5 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 13,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        colormap           = [[1.0 0.6 0.4 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 13,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.4,
        color              = [[1.0, 0.8, 0.5]],
        dir                = [[-2 r4,-2 r4,-2 r4]],
        length             = 1,
        width              = 11,
      },
    },
  },

  ["greencrap"] = {
    usedefaultexplosions = false,
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.3,
      flashsize          = 30,
      ground             = true,
      ttl                = 10,
      water              = true,
      color = {
        [1]  = 0.10000000149012,
        [2]  = 0.89999997615814,
        [3]  = 0.10000000149012,
      },
    },
  },

  ["nucklearnanocatapult"] = {
    usedefaultexplosions = false,
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.45 0.2 0.4 1.0 0.3 0.2 0.01 0 0 0 0.01]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 1,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 12,
        particlelifespread = 3,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 7,
        particlespeedspread = 5,
        pos                = [[0, 1, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[smoke1]],
      },
    },
  },

  ["nucklearnanocir"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.4,
        colormap           = [[1 0.88 0.15 0.2 0.1 0.05 0.0 0.2 0.0 0.0 0.0 0.3 0.0 0.0 0.0 0.3]],
        directional        = false,
        emitrot            = 3,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 1,
        particlelifespread = 2,
        particlesize       = 1.2,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 9,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[0.95 0.58 0.0 0.4 0.85 0.42 0.0 0.3 0.0 0.0 0.0 0.3 0.0 0.0 0.0 0.2]],
        directional        = false,
        emitrot            = 5,
        emitrotspread      = 3,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 2,
        particlelifespread = 2,
        particlesize       = 2.3,
        particlesizespread = 1,
        particlespeed      = 10,
        particlespeedspread = 7,
        pos                = [[0, -2, 0]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[1.0, 0.7, 0.3]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 2.5,
        width              = 2.5,
      },
    },
  },

}

